    // Generated by Bisonc++ V4.05.00 on Fri, 31 Oct 2014 01:06:39 +0530

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
// $insert scanner.h
#include "scanner.h"
#include "parserbase.h"


#undef Parser
class Parser: public ParserBase
{
    // $insert scannerobject
    Scanner d_scanner;
        
    public:
        Parser()
        {
                d_scanner.setSval(&d_val__);
        }
        int parse();

    private:
        void error(char const *msg);    // called on (syntax) errors
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc

    // support functions for parse():
        void executeAction(int ruleNr);
        void errorRecovery();
        int lookup(bool recovery);
        void nextToken();
        void print__();
        void exceptionHandler__(std::exception const &exc);
};

#endif
